### ISSUE TITLE
3D Second Harmonic Images

### ISSUE THREAD

**Issue by ahsusohail** [wershofe/TWOMBLI#11]
Hi, 

I have been trying to use TWOMBLI to quantify fibrosis acquired through second harmonic imaging in kidney biopsy specimens. 

TWOMBLI is working well for 2D images, but I am having trouble with the 3D images, since the mask and HDM images are not produced well with 3D images. 

Would you be able to help me understand how to process 3D biopsy specimens with TWOMBLI? 

Thank you!

**Comment by wershofe** [comment]
Hi
Unfortunately TWOMBLI doesn't currently have the capability to construct and quantify 3D masks
