### ISSUE TITLE
Error: function processFolderRidgeDetection

### ISSUE THREAD

**Issue by SimoniMD** [wershofe/TWOMBLI#2]
H! Thanks for this package. I'm gotten past the part where you se the parameters, and i'm trying to run the program, but getting the following error and unsure what it means:

```
Error:		1 argument expected in line 883:
		(called from line 889)
		(called from line 554)
	
		function processFolderRidgeDetection ( input , <output> ) { 

```
Any advice? Below are all my settings:

EOL (g)	*	" | "
PARAM_FILE_NAME (g)	*	"parameters.txt"
HDM_RESULTS_FILENAME (g)	*	"_ResultsHDM.csv"
ANAMORF_RESULTS_FILENAME (g)	*	"results.csv"
TWOMBLI_RESULTS_FILENAME (g)	*	"Twombli_Results"
contrastSaturation (g)	*	0.3500
minLineWidth (g)	*	10
maxLineWidth (g)	*	10
minCurvatureWindow (g)	*	40
maxCurvatureWindow (g)	*	40
curvatureWindowStep (g)	*	10
minimumBranchLength (g)	*	10
maximumDisplayHDM (g)	*	200
gapAnalysis (g)	*	1
minimumGapDiameter (g)	*	68
minLineWidthTest (g)	*	5
maxLineWidthTest (g)	*	20
contrastHigh (g)	*	120
contrastLow (g)	*	0
outputMasks (g)	*	"D:\Jurado Lab\Simoni\Jan2022\Twombli\Masks\"
darkline (g)	*	0
dimensionsVec (g)	*	array[0]
alignmentVecOrder (g)	*	array[0]
happyWithValues	*	1
happyRealFolders	*	1
inputEligible	*	"D:\Jurado Lab\Simoni\Jan2022\Twombli\OriginalFiles\Eligible\"
outputHDM	*	"D:\Jurado Lab\Simoni\Jan2022\Twombli\HDM\"
anamorfProperties	*	"C:\Users\Nikon Passive\Desktop\TWOMBLI-master\TWOMBLI_v1\programs\AnamorfPropert..."
output	*	"D:\Jurado Lab\Simoni\Jan2022\Twombli\Masks\"
input	*	"D:\Jurado Lab\Simoni\Jan2022\Twombli\OriginalFiles\Eligible\"
list	*	array[5]
output	*	3
input	*	"D:\Jurado Lab\Simoni\Jan2022\Twombli\OriginalFiles\Eligible\\HDM/"

**Comment by djpbarry** [comment]
Hi @SimoniMD,

Thanks for flagging this.

I've just pushed a change which hopefully fixes this issue - can you try the new version of the code and let me know?
