### ISSUE TITLE
Processing fluorescence images and receiving "LUT reset" window

### ISSUE THREAD

**Issue by clairemitchell308** [wershofe/TWOMBLI#3]
Hello

I am running TWOMBLI on some fluorescence images and am encoutering a small bug.

When running through the whole parameter determination steps. Upon generating the masks, I receive the following window 

"LUT reset: The LUT of your image is inverted and will now reset for better parameter selection". 

This then opens up the Ridge Detection GUI which I then have to select "OK" manually to continue, this then happens for each image the software generates a mask for. Everything still works but it would just be a bit annoying should I want to run the software over a large number of images. 

I have attached an [example image](https://github.com/wershofe/TWOMBLI/files/11222335/fluorescent_matrix.zip), I would be interested to hear if you encounter the same error. I don't believe it's to do with it being a fluorescence image as I understand this should work on fluorescence images as well?

Many thanks and best wishes
Claire

**Comment by wershofe** [comment]
Hi
I don't think there is a quick fix within TWOMBLI for this. One option is to Invert the LUT for all the images in bulk from Fiji and save them in a different "inverted" folder - then TWOMBLI won't try to correct each image. Can you give this a try and see if it works?
