### ISSUE TITLE
Gap analysis doesn't use user supplied minimum diameter and also doesn't produce overlaid .pngs 

### ISSUE THREAD

**Issue by clairemitchell308** [wershofe/TWOMBLI#4]
Hello

I have found what I believe is a mistake in the optional gap analysis. The user supplies a minimum circle diameter, but the gap analysis then uses a set circle diameter in the code (line 1153):

`run("Max Inscribed Circles", "minimum=30 use minimum_0=0.50 closeness=5");`

Also, running TWOMBLI on my laptop (windows), it doesn't produce the overlaid .png images showing the results of the gap analysis. I tried for a long time to debug this but have been unsuccessful. When I run the gap analysis individually on an open image and show all, flatten etc then it works fine but running inside the macro for some reason the images saved are just the masks with no overlaid circles. The gap analysis is running okay, it's only the images which is the problem.

**Comment by djpbarry** [comment]
Hi @clairemitchell308,

Thanks for spotting this - I've just pushed a commit to address the first issue.

Regarding the second issue, I'm seeing the same thing - might require some more time to investigate.

**Comment by djpbarry** [comment]
Hi @clairemitchell308,

I've just pushed a commit which I think addresses the second issue - should be behaving as expected now.
