### ISSUE TITLE
AnaMorf Macro Extension doesn't work

### ISSUE THREAD

**Issue by MatUTw** [wershofe/TWOMBLI#5]
At the end of the analysis it shows the following and doesn't deliver the data.
Error:		Unrecognized command: "AnaMorf Macro Extensions" in line 578:		run ( "AnaMorf Macro Extensions" <)> ; 
[Debug.csv](https://github.com/wershofe/TWOMBLI/files/11308567/Debug.csv)

**Comment by wershofe** [comment]
Hi
Have you checked if you have installed the Anamorf plugin and that it is in the same folder as your other Fiji plugins?
