### ISSUE TITLE
Problem running TWOMBLI

### ISSUE THREAD

**Issue by Pyoung99** [wershofe/TWOMBLI#6]
I have been having an issue while trying to run the tutorial. Each time it ends in the error: "Error: Undefined identifier in line 1221: (called from line 600) list2 = <append> ( list2 , list [ j ] ) ; ". I haven't been able to find a way around it. Any ideas?

**Comment by Pyoung99** [comment]
Update: I downloaded the version 1 of the code and it works just fine. Possibly an issue with the new version?

**Comment by George-Thompson** [comment]
I'm having the exact same issue, in the tutorial and using my own images, and can also get round it by using the first release code.
I'd appreciate if someone could have a look at this, I'd really like to try using the multiple line widths feature in the newer version.

**Comment by djpbarry** [comment]
Hi @Pyoung99,

Thanks for flagging this - I neglected to remove some references to defunct functions in a previous commit.

I've just pushed a fresh commit to address the problem.
