### ISSUE TITLE
Code error after anamorph analysis

### ISSUE THREAD

**Issue by SaraCampi** [wershofe/TWOMBLI#7]
Hi there, a code error appears after anamorph analysis and the macro stop progressing. Please take a look at the screenshot I've attached. Can you help, please? 
Thank you!
Sara
<img width="1512" alt="Screenshot 2023-07-19 at 13 08 57" src="https://github.com/wershofe/TWOMBLI/assets/139995783/9b608bdd-1515-4325-86a0-a86e5bd14a2a">

**Comment by wershofe** [comment]
I couldn't replicate this error - could you confirm that the CALM plugin is up to date?

**Comment by SaraCampi** [comment]
Hi there, it was my fault- accidentally I hadn't downloaded one of the necessary plug-ins! Thank you so much for your support!

**Comment by wershofe** [comment]
Great, I'll close the issue
